Update check_new_PR_remove_label.yml

diff --git a/.github/workflows/check_new_PR_remove_label.yml b/.github/workflows/check_new_PR_remove_label.yml
--- a/.github/workflows/check_new_PR_remove_label.yml
+++ b/.github/workflows/check_new_PR_remove_label.yml
@@ -78,14 +78,13 @@ jobs:
               }
             }
 
-  jobs:
-    do-not-merge:
-      if: ${{ contains(github.event.*.labels.*.name, 'New PR') }}
-      name: Prevent New PR Merging
-      runs-on: ubuntu-latest
-      steps:
-        - name: Check for New PR label
-          run: |
-            echo "Pull request is labeled as 'New PR'"
-            echo "This workflow fails so that the pull request cannot be merged"
-            exit 1
+  do-not-merge:
+    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
+    name: Prevent Merging
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for label
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1
